# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e85484e547bb60fe353592356a345ed1"
name = "PriceGuard"
application_url = "https://priceguard.sample-guard.com"
embedded = true
handle = "priceflow-app"

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://priceguard.sample-guard.com/auth/callback" ]

[app_preferences]
url = "https://priceguard.sample-guard.com/settings"








[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "/webhooks/compliance"
